version: '3'
services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile.local
    environment:
      - MYSQL_DATABASE=enodb
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    # ports:
    #   - "3306:3306"
    restart: "always"
  buggy:
    build:
        context: .
        dockerfile: Dockerfile.local
    volumes:
      - ./buggy:/go/src/buggy
    ports:
      - "7890:7890"
    restart: "always"
    environment:
      - MYSQL_DATABASE=enodb
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mysql
