version: '3'
services:
  mysql:
    build: ./mysql
    environment:
      - MYSQL_DATABASE=enodb
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: "always"
  buggy:
    build: .
    volumes:
      - ./buggy:/go/src/buggy
    ports:
      - "7890:7890"
    environment:
      - MYSQL_DATABASE=enodb
      - MYSQL_ROOT_PASSWORD=root
    restart: "always"
    depends_on:
      - mysql
