version: '3'

services:
  buggy-backend:
    build: .
    ports:
      - 7891:3031
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=buggy-db
     - MONGO_PORT=27017
     - MONGO_USER=enoislove
     - MONGO_PASSWORD=enoislife
  buggy-db:
    image: mongo
    volumes:
      - ./buggy_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: enoislove
      MONGO_INITDB_ROOT_PASSWORD: enoislife
